#!/bin/bash -xe

export WORKSPACE=/home/test
REPO_BASE=midonet

if [ ".$1" != "." ]; then
    REPO_BASE=$1
fi

cd $WORKSPACE
./pull_source -r $REPO_BASE -d mdts mdts

./mdts/setup_test_server
./mdts/mdts_cbt -s source midonet master
