#!/bin/bash -xe

SOURCE_BRANCH=master
GIT_SERVER=http://github.com
REPO_BASE=midonet
REPO_PRODUCT=

function usage()
{
    echo "Usage: $0 [-b <branch=master> ] [ -r <repo_base=midonet> ] [ -d <dest_location=midonet>] <code_base>"
}

while [ "$1" != "" ]; do
    case $1 in
        -b | --branch )
            shift
            SOURCE_BRANCH=$1
            ;;
        -r | --repository )
            shift
            REPO_BASE=$1
            ;;
        -d | --destination )
            shift
            DEST_LOC=$1
            ;;
        -h | --help )
            usage
            exit
            ;;
        * )
            REPO_PRODUCT=$1
	    ;;
    esac
    shift
done

if [ ".$REPO_PRODUCT" == "." ]; then
    usage
    exit 1
fi

git clone $GIT_SERVER/$REPO_BASE/$REPO_PRODUCT -b $SOURCE_BRANCH $DEST_LOC

